version: '3.8'

services:
    app:
        build: .
        command: ./docker/start
        container_name: app
        environment:
            USERID: $(id -u)
            GROUPID: $(id -g)
        networks:
            - local
        ports:
            - 3000:3000
        volumes:
            - .:/app
        tty: true

volumes:
    db: null

networks:
    local: {}
